### ISSUE TITLE
set_header_func causes panic on !ptr.is_null()

### ISSUE THREAD

**Issue by mmstick** [gtk-rs/gtk#797]
I have a `ListBox` with the header func being set:

```rust
let list = cascade! {
    gtk::ListBox::new();
    ..set_hexpand(true);
    ..set_valign(gtk::Align::Start);
    ..get_style_context().add_class("view");
    ..set_selection_mode(gtk::SelectionMode::None);
    ..set_header_func(Some(Box::new(crate::utils::separator_header)));
};
```
Where `crate::utils::separator_header` is defined as:

```rust
pub(crate) fn separator_header(row1: &gtk::ListBoxRow, row2: &gtk::ListBoxRow) {
    row2.set_header(&gtk::Separator::new(gtk::Orientation::Horizontal));
}
```

As I add rows to the list box, I get a panic:

```
thread 'main' panicked at 'assertion failed: !ptr.is_null()', /home/mmstick/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.7.1/src/shared.rs:403:9
```

It seems to be panicking before the `separator_header()` is called.

**Comment by sdroege** [comment]
Can you debug print each of the parameters passed to the function that crashes? I.e. with `{:?}`.

Also please provide a full backtrace by reproucing with `RUST_BACKTRACE=1` so we can see where exactly it comes from. One of the parameters passed here to a function is `NULL` while it shouldn't really. Which probably means that a function should actually return an `Option` but currently doesn't.

**Comment by mmstick** [comment]
The panic happens outside of the `separator_header` function, so I'll need to add the debug lines to gtk-rs itself. I didn't include the backtrace because it wasn't very descriptive.

```
thread 'main' panicked at 'assertion failed: !ptr.is_null()', /home/mmstick/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.7.1/src/shared.rs:403:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::begin_panic
   6: <O as gtk::auto::list_box::ListBoxExt>::set_header_func::update_header_func
   7: <unknown>
   8: gtk_list_box_insert
   9: <core::iter::Map<I, F> as core::iter::iterator::Iterator>::fold
  10: glib::source::trampoline
  11: <unknown>
  12: g_main_context_dispatch
  13: <unknown>
  14: g_main_context_iteration
  15: g_application_run
  16: system76_receiving_gtk::main
  17: std::rt::lang_start::{{closure}}
  18: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  19: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  20: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  21: main
  22: __libc_start_main
  23: _start
```

**Comment by mmstick** [comment]
Fixed my makefile

```
   5: std::panicking::begin_panic
             at libstd/panicking.rs:410
   6: <gtk::auto::list_box_row::ListBoxRow as glib::translate::FromGlibPtrBorrow<*mut gtk_sys::GtkListBoxRow>>::from_glib_borrow
             at /home/mmstick/Sources/gtk/gtk/<::glib::object::glib_object_wrapper macros>:113
   7: glib::translate::from_glib_borrow
             at /home/mmstick/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.7.1/src/translate.rs:1092
   8: <O as gtk::auto::list_box::ListBoxExt>::set_header_func::update_header_func
             at /home/mmstick/Sources/gtk/gtk/src/auto/list_box.rs:316
```

**Comment by mmstick** [comment]
In

```rust
unsafe extern "C" fn update_header_func(row: *mut ffi::GtkListBoxRow, before: *mut ffi::GtkListBoxRow, user_data: glib_ffi::gpointer) {
    let row = from_glib_borrow(row);
    let before = from_glib_borrow(before);
    let callback: &Option<Box<dyn Fn(&ListBoxRow, &ListBoxRow) + 'static>> = &*(user_data as *mut _);
    if let Some(ref callback) = *callback {
        callback(&row, &before)
    } else {
        panic!("cannot get closure...")
    };
}
```

The `row` input parameter is a null pointer.

**Comment by mmstick** [comment]
It doesn't panic anymore after changing the signature from

```rust
fn set_header_func(&self, update_header: Option<Box<dyn Fn(&ListBoxRow, &ListBoxRow) + 'static>>);` 
```

to

```rust
fn set_header_func(&self, update_header: Option<Box<dyn Fn(&ListBoxRow, Option<&ListBoxRow>) + 'static>>);
```

and modifying the impl accordingly

```rust
fn set_header_func(&self, update_header: Option<Box<dyn Fn(&ListBoxRow, Option<&ListBoxRow>) + 'static>>) {
    let update_header_data: Box_<Option<Box<dyn Fn(&ListBoxRow, Option<&ListBoxRow>) + 'static>>> = Box::new(update_header);
    unsafe extern "C" fn update_header_func(row: *mut ffi::GtkListBoxRow, before: *mut ffi::GtkListBoxRow, user_data: glib_ffi::gpointer) {
        let row = from_glib_borrow(row);
        let before = if before.is_null() { None } else { from_glib_borrow(before) };
        let callback: &Option<Box<dyn Fn(&ListBoxRow, Option<&ListBoxRow>) + 'static>> = &*(user_data as *mut _);
        if let Some(ref callback) = *callback {
            callback(&row, before.as_ref())
        } else {
            panic!("cannot get closure...")
        };
    }
    let update_header = if update_header_data.is_some() { Some(update_header_func as _) } else { None };
    unsafe extern "C" fn destroy_func(data: glib_ffi::gpointer) {
        let _callback: Box_<Option<Box<dyn Fn(&ListBoxRow, Option<&ListBoxRow>) + 'static>>> = Box_::from_raw(data as *mut _);
    }
    let destroy_call3 = Some(destroy_func as _);
    let super_callback0: Box_<Option<Box<dyn Fn(&ListBoxRow, Option<&ListBoxRow>) + 'static>>> = update_header_data;
    unsafe {
        ffi::gtk_list_box_set_header_func(self.as_ref().to_glib_none().0, update_header, Box::into_raw(super_callback0) as *mut _, destroy_call3);
    }
}
```

**Comment by sdroege** [comment]
Same as https://github.com/gtk-rs/glib/issues/466 then. nullable/allow-none parameters to callbacks are handled incorrectly (or rather: not at all).

**Comment by GuillaumeGomez** [comment]
Then I need to fix it! Opening the issue on gir.

**Comment by sdroege** [comment]
@GuillaumeGomez This is fixed now or not?

**Comment by GuillaumeGomez** [comment]
Normally it is.

**Comment by sdroege** [comment]
Then please close it :) https://github.com/gtk-rs/gtk/pull/798 should've fixed this.
