### ISSUE TITLE
Setting gtk::HeaderBarExt::set_show_close_button() causes program to crash 	

### ISSUE THREAD

**Issue by HossainAdnan** [gtk-rs/gtk#891]
```rust
use gio::prelude::*;
use gtk::{
    prelude::*,
    HeaderBarExt,
    GtkWindowExt
};

pub mod consts {
    pub static APP_ID: &'static str = "com.github.apptest";
}

fn gen_header_bar(subtitle: Option<String>) -> gtk::HeaderBar {
    let header_bar = gtk::HeaderBar::new();
    header_bar.set_title(Some(consts::APP_ID));
    header_bar.set_show_close_button(true); // <-- causes the crash
    match subtitle {
        Some(subtitle) => {
                header_bar.set_subtitle(Some(&subtitle));
            },
        _ => {
        }
    }
    header_bar
}


pub fn build_application_window() -> Result<(), Box<dyn std::error::Error>> {
    let application = gtk::Application::new(
        Some(consts::APP_ID),
        Default::default(),
    )?;

    application.connect_activate(|app| {
        let window = gtk::ApplicationWindow::new(app);
        window.set_title(consts::APP_ID);
        window.set_default_size(32 * 10, 200); // golden ratio
        window.set_position(gtk::WindowPosition::Center);

        let header_bar = gen_header_bar(None);
        window.set_titlebar(Some(&header_bar));

        let vbox = gtk::Box::new(gtk::Orientation::Vertical, 5);

        let label = gtk::Label::new(Some("Welcome!"));
        vbox.pack_start(&label, false, false, 5);

        window.add(&vbox);

        println!("Reached upto here.");
        window.show_all(); // <-- crashes here
    });

    application.run(&std::env::args().collect::<Vec<_>>());

    Ok(())
}

fn main() {
    build_application_window().expect("GTK app failed");
}
```

Cargo.toml:
```toml
[package]
name = "testbed_rs"
version = "0.1.0"
authors = ["user0"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.7.0"
glib = "0.8.1"

[dependencies.gtk]
version = "0.7.0"
features = ["v3_22"]
```

Output:
Segfaults in runtime with no other messages.

Platform:
```
[user0@primarypc ~]$ pacman -Qiv gtk3 gnome-desktop
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : gtk3  gnome-desktop
Name            : gtk3
Version         : 1:3.24.10-1
Description     : GObject-based multi-platform GUI toolkit
Architecture    : x86_64
URL             : https://www.gtk.org/
Licenses        : LGPL
Groups          : None
Provides        : gtk3-print-backends
Depends On      : atk  cairo  libxcursor  libxinerama  libxrandr  libxi  libepoxy  gdk-pixbuf2  dconf  libxcomposite  libxdamage  pango
                  shared-mime-info  at-spi2-atk  wayland  libxkbcommon  adwaita-icon-theme  json-glib  librsvg  wayland-protocols
                  desktop-file-utils  mesa  cantarell-fonts  colord  rest  libcups  libcanberra  fribidi  iso-codes
                  gtk-update-icon-cache
Optional Deps   : None
Required By     : appstream-glib  baobab  caffeine-ng  cheese  clutter  colord-gtk  dconf-editor  evince  file-roller  firefox  gcr  gjs
                  gnome-autoar  gnome-bluetooth  gnome-books  gnome-calculator  gnome-characters  gnome-clocks  gnome-contacts
                  gnome-control-center  gnome-desktop  gnome-disk-utility  gnome-font-viewer  gnome-screenshot  gnome-session
                  gnome-settings-daemon  gnome-system-log  gnome-user-share  gnome-weather  gspell  gthumb  gtkmm3  gtksourceview3
                  gtksourceview4  gtkspell3  gufw  kazam  libcryptui  libdazzle  libgnomekbd  libgweather  libgxps  libhandy
                  libnautilus-extension  libnma  libpeas  libwnck3  lollypop  manjaro-application-utility  manjaro-hello
                  matcha-gtk-theme  mousetweaks  nixwriter  pamac-gtk  polari  polkit-gnome  seahorse  simple-scan
                  system-config-printer  timeshift  transmission-gtk  uget  vino  vte3  webkit2gtk  xdg-desktop-portal-gtk
                  xdg-user-dirs-gtk  yad
Optional For    : avahi  ghostscript  grilo  gssdp  gvfs  jre-openjdk  jre11-openjdk  libinput  libreoffice-still  pacman-mirrors
                  qt5-base  stoken
Conflicts With  : gtk3-print-backends
Replaces        : gtk3-print-backends<=3.22.26-1
Installed Size  : 72.74 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Thu 04 Jul 2019 21:02:41 AEST
Install Date    : Mon 26 Aug 2019 14:58:54 AEST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature

Name            : gnome-desktop
Version         : 1:3.32.2-1
Description     : Library with common API for various GNOME modules
Architecture    : x86_64
URL             : https://gitlab.gnome.org/GNOME/gnome-desktop
Licenses        : GPL  LGPL
Groups          : None
Provides        : None
Depends On      : gsettings-desktop-schemas  gtk3  libxkbfile  xkeyboard-config  iso-codes  libseccomp  bubblewrap
Optional Deps   : None
Required By     : cheese  evince  evolution  gnome-books  gnome-characters  gnome-clocks  gnome-contacts  gnome-control-center
                  gnome-font-viewer  gnome-session  gnome-settings-daemon  gnome-weather  kazam  mutter  nautilus  totem
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 3.05 MiB
Packager        : Jan Alexander Steffens (heftig) <jan.steffens@gmail.com>
Build Date      : Tue 07 May 2019 23:37:37 AEST
Install Date    : Mon 26 Aug 2019 14:59:05 AEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by EPashkin** [comment]
On windows10 and mingw64 I get both "Reached upto here." and normal window.

**Comment by HossainAdnan** [comment]
In my up-to-date Manjaro system, the application segfaults. I'll report if the issue persists in another distribution later.
[Image](https://imgur.com/a/8g18ny8)

**Comment by sdroege** [comment]
Please get a backtrace of the segmentation fault (after installing debug packages for at least glibc, glib, gdk and gtk).

**Comment by HossainAdnan** [comment]
I'm not entirely familiar with using gdb, hence if I run with `RUST_BACKTRACE=1 cargo run`, it doesn't provide anything new. Using `rust-gdb` says:
```
]$ rust-gdb ./target/debug/dbustest_rs
GNU gdb (GDB) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./target/debug/dbustest_rs...
(gdb) r
Starting program: /home/user0/vscproj/dbustest_rs/target/debug/dbustest_rs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

(process:5735): Gtk-WARNING **: 16:58:30.480: Locale not supported by C library.
	Using the fallback 'C' locale.
[New Thread 0x7ffff54b3700 (LWP 5739)]
[New Thread 0x7ffff4cb2700 (LWP 5740)]
Reached upto here.

Thread 1 "dbustest_rs" received signal SIGSEGV, Segmentation fault.
0x00007ffff723dd54 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
(gdb) 
```

**Comment by sdroege** [comment]
On the gdb prompt, do `backtrace` and press enter until you're back at the prompt.

**Comment by HossainAdnan** [comment]
> On the gdb prompt, do `backtrace` and press enter until you're back at the prompt.

```
Thread 1 "dbustest_rs" received signal SIGSEGV, Segmentation fault.
0x00007ffff723dd54 in __memmove_avx_unaligned_erms () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff723dd54 in __memmove_avx_unaligned_erms () at /usr/lib/libc.so.6
#1  0x00007ffff62ec326 in  () at /usr/lib/libpng16.so.16
#2  0x00007ffff62dbed4 in  () at /usr/lib/libpng16.so.16
#3  0x00007ffff62dc3b5 in  () at /usr/lib/libpng16.so.16
#4  0x00007ffff62dc69f in  () at /usr/lib/libpng16.so.16
#5  0x00007ffff62dc88c in png_process_data () at /usr/lib/libpng16.so.16
#6  0x00007fffefbabcd9 in  ()
    at /snap/code/14/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
#7  0x00007ffff7628c45 in  () at /usr/lib/libgdk_pixbuf-2.0.so.0
#8  0x00007ffff7628e35 in gdk_pixbuf_loader_close () at /usr/lib/libgdk_pixbuf-2.0.so.0
#9  0x00007ffff762989c in  () at /usr/lib/libgdk_pixbuf-2.0.so.0
#10 0x00007ffff76298fd in gdk_pixbuf_new_from_stream () at /usr/lib/libgdk_pixbuf-2.0.so.0
#11 0x00007ffff7b6fde2 in  () at /usr/lib/libgtk-3.so.0
#12 0x00007ffff7b736ba in  () at /usr/lib/libgtk-3.so.0
#13 0x00007ffff7b77bac in  () at /usr/lib/libgtk-3.so.0
#14 0x00007ffff7b78142 in  () at /usr/lib/libgtk-3.so.0
#15 0x00007ffff7b78259 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007ffff7b78510 in  () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff7b611f1 in  () at /usr/lib/libgtk-3.so.0
#18 0x00007ffff7bfca33 in  () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff7c02771 in  () at /usr/lib/libgtk-3.so.0
#20 0x00007ffff7b5cba3 in  () at /usr/lib/libgtk-3.so.0
#21 0x00007ffff7aa1bf3 in  () at /usr/lib/libgtk-3.so.0
#22 0x00007ffff7aa0bde in  () at /usr/lib/libgtk-3.so.0
#23 0x00007ffff7aa0ce5 in gtk_widget_get_preferred_height_and_baseline_for_width ()
    at /usr/lib/libgtk-3.so.0
#24 0x00007ffff7bfca33 in  () at /usr/lib/libgtk-3.so.0
#25 0x00007ffff7c02771 in  () at /usr/lib/libgtk-3.so.0
#26 0x00007ffff7c46493 in  () at /usr/lib/libgtk-3.so.0
#27 0x00007ffff7aa1bf3 in  () at /usr/lib/libgtk-3.so.0
#28 0x00007ffff7aa0bde in  () at /usr/lib/libgtk-3.so.0
#29 0x00007ffff7aa0ce5 in gtk_widget_get_preferred_height_and_baseline_for_width ()
    at /usr/lib/libgtk-3.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#30 0x00007ffff7c55c1c in  () at /usr/lib/libgtk-3.so.0
#31 0x00007ffff7bfca33 in  () at /usr/lib/libgtk-3.so.0
#32 0x00007ffff7c02771 in  () at /usr/lib/libgtk-3.so.0
#33 0x00007ffff7c4f803 in  () at /usr/lib/libgtk-3.so.0
#34 0x00007ffff7aa1bf3 in  () at /usr/lib/libgtk-3.so.0
#35 0x00007ffff7aa0bde in  () at /usr/lib/libgtk-3.so.0
#36 0x00007ffff7aa0f21 in gtk_widget_get_preferred_height () at /usr/lib/libgtk-3.so.0
#37 0x00007ffff7b7c784 in  () at /usr/lib/libgtk-3.so.0
#38 0x00007ffff7b7cd67 in  () at /usr/lib/libgtk-3.so.0
#39 0x00007ffff7bfca33 in  () at /usr/lib/libgtk-3.so.0
#40 0x00007ffff7c02771 in  () at /usr/lib/libgtk-3.so.0
#41 0x00007ffff7b79dfd in  () at /usr/lib/libgtk-3.so.0
#42 0x00007ffff7aa16ae in  () at /usr/lib/libgtk-3.so.0
#43 0x00007ffff7aa0bde in  () at /usr/lib/libgtk-3.so.0
#44 0x00007ffff7aa0f21 in gtk_widget_get_preferred_height () at /usr/lib/libgtk-3.so.0
#45 0x00007ffff79d6424 in  () at /usr/lib/libgtk-3.so.0
#46 0x00007ffff7c5c2ce in  () at /usr/lib/libgtk-3.so.0
#47 0x00007ffff7aa16ae in  () at /usr/lib/libgtk-3.so.0
#48 0x00007ffff7aa0bde in  () at /usr/lib/libgtk-3.so.0
#49 0x00007ffff7aa0ce5 in gtk_widget_get_preferred_height_and_baseline_for_width () at /usr/lib/libgtk-3.so.0
#50 0x00007ffff793a16c in  () at /usr/lib/libgtk-3.so.0
#51 0x00007ffff79da443 in  () at /usr/lib/libgtk-3.so.0
#52 0x00007ffff79dd922 in  () at /usr/lib/libgtk-3.so.0
#53 0x00007ffff7c5ee73 in  () at /usr/lib/libgtk-3.so.0
#54 0x00007ffff743fcaa in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#55 0x00007ffff742d854 in  () at /usr/lib/libgobject-2.0.so.0
#56 0x00007ffff743189a in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#57 0x00007ffff7432700 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#58 0x00007ffff793ccdd in gtk_widget_realize () at /usr/lib/libgtk-3.so.0
#59 0x00007ffff79dbdce in  () at /usr/lib/libgtk-3.so.0
#60 0x00007ffff743fcaa in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#61 0x00007ffff742d854 in  () at /usr/lib/libgobject-2.0.so.0
#62 0x00007ffff743189a in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#63 0x00007ffff7432700 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#64 0x00007ffff79f764a in gtk_widget_show () at /usr/lib/libgtk-3.so.0
#65 0x000055555555ed09 in <O as gtk::auto::widget::WidgetExt>::show_all (self=0x7fffffffcf78) at /home/user0/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.7.0/src/auto/widget.rs:2675
#66 0x000055555555caac in dbustest_rs::build_application_window::{{closure}} (app=0x7fffffffd0a8) at src/main.rs:50
#67 0x000055555555eb8c in <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline (this=0x5555558f50f0, f=0x1)
    at /home/user0/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.7.0/src/auto/application.rs:546
#68 0x00007ffff743fcaa in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#69 0x00007ffff742d706 in  () at /usr/lib/libgobject-2.0.so.0
#70 0x00007ffff743189a in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#71 0x00007ffff7432700 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#72 0x00007ffff75069f9 in  () at /usr/lib/libgio-2.0.so.0
#73 0x00007ffff7506536 in g_application_run () at /usr/lib/libgio-2.0.so.0
#74 0x000055555555d824 in <O as gio::application::ApplicationExtManual>::run (self=0x7fffffffd710, argv=&[alloc::string::String](len: 1) = {...})
    at /home/user0/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.7.0/src/application.rs:23
#75 0x000055555556054d in dbustest_rs::build_application_window () at src/main.rs:54
#76 0x0000555555560629 in dbustest_rs::main () at src/main.rs:60
```

**Comment by sdroege** [comment]
Not too useful, as said you need to install debug packages for various libraries. Which is unfortunately rather complicated on Arch. It's not a great development platform.

For your crash, that looks like a problem in libpng or the corresponding gdk-pixbuf loader, unrelated to the headerbar or the Rust bindings.

**Comment by HossainAdnan** [comment]
Ok looks like it's distro specific. Closing.
This encourages me to look more into flatpaks.
