### ISSUE TITLE
ListBox's unselect_row and unselect_all methods cause a panic

### ISSUE THREAD

**Issue by gmg137** [gtk-rs/gtk#909]
when I want to delete the row, I find that if the row is selected, it will cause a crash.

When I want to use unselect_row() I find that it also crashes.

**Comment by sdroege** [comment]
Can you provide a) a testcase to reproduce the problem and b) a backtrace and console output for the crash? Thanks!

**Comment by gmg137** [comment]
This is my code
```
    pub(crate) fn update_sidebar(&self, group_list: Vec<String>) {
        self.sidebar.foreach(|w| {
            // Crash here
            self.sidebar.remove(w);
        });

        group_list.iter().for_each(|sl| {
            let label = Label::new(Some(&sl));
            label.set_halign(gtk::Align::Start);
            label.set_valign(gtk::Align::Fill);
            label.set_margin_start(18);
            label.set_ellipsize(pango::EllipsizeMode::End);
            label.set_max_width_chars(16);
            let row = ListBoxRow::new();
            row.set_property_height_request(53);
            row.add(&label);
            self.sidebar.insert(&row, -1);
        });
        if let Some(one_row) = self.sidebar.get_row_at_index(0) {
            self.sidebar.select_row(Some(&one_row));
        }
        self.sidebar.show_all();
    }
```

This is the error output:
> $ RUST_BACKTRACE=full cargo run
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0:     0x5652e03d4afb - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x5652e03d4afb - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x5652e03d4afb - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x5652e03d4afb - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x5652e03d4afb - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x5652e03d47d6 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5652e03d51bd - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5652e03d4d42 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x5652e03d4c26 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x5652e03edbed - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x5652e03edb2c - core::panicking::panic::hda536e6f3accfb91
                               at src/libcore/panicking.rs:49
  11:     0x5652e035ebcb - core::option::Option<T>::unwrap::hcfaa460efe1c0465
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/macros.rs:12
  12:     0x5652e0392dea - shadowsocksr_gtk::view::home::Home::init::{{closure}}::h4d210f21ac35c1a3
                               at src/view/home.rs:65
  13:     0x5652e0385655 - <O as gtk::auto::list_box::ListBoxExt>::connect_row_selected::row_selected_trampoline::h7820c60902df352f
                               at /home/gmg/.cargo/registry/src/code.aliyun.com-738b7dba08a2a41e/gtk-0.7.0/src/auto/list_box.rs:1035
  14:     0x7ff4cd05168f - g_cclosure_marshal_VOID__OBJECTv
  15:     0x7ff4cd041d4f - g_signal_emit_valist
  16:     0x7ff4cd0429ff - g_signal_emit
  17:     0x7ff4cd70edc7 - <unknown>
  18:     0x7ff4cd05168f - g_cclosure_marshal_VOID__OBJECTv
  19:     0x7ff4cd041d4f - g_signal_emit_valist
  20:     0x7ff4cd0429ff - g_signal_emit
  21:     0x7ff4cd7d1e83 - gtk_container_remove
  22:     0x5652e0385849 - <O as gtk::auto::container::ContainerExt>::remove::h710bea1c31561fc8
                               at /home/gmg/.cargo/registry/src/code.aliyun.com-738b7dba08a2a41e/gtk-0.7.0/src/auto/container.rs:279
  23:     0x5652e0392f26 - shadowsocksr_gtk::view::home::Home::update_sidebar::{{closure}}::hf2d22f55b585d124
                               at src/view/home.rs:89
  24:     0x5652e035ce76 - <O as gtk::auto::container::ContainerExt>::foreach::callback_func::hd090a8ba71831332
                               at /home/gmg/.cargo/registry/src/code.aliyun.com-738b7dba08a2a41e/gtk-0.7.0/src/auto/container.rs:205
  25:     0x7ff4cd706fe9 - <unknown>
  26:     0x5652e0385924 - <O as gtk::auto::container::ContainerExt>::foreach::h8dfc68fe68ee3564
                               at /home/gmg/.cargo/registry/src/code.aliyun.com-738b7dba08a2a41e/gtk-0.7.0/src/auto/container.rs:210
  27:     0x5652e0390055 - shadowsocksr_gtk::view::home::Home::update_sidebar::h1c4a316fb18e3fa1
                               at src/view/home.rs:87
  28:     0x5652e038357d - shadowsocksr_gtk::view::View::update_home_sidebar::h022d03ff07a88f82
                               at src/view/mod.rs:42
  29:     0x5652e0361c0d - shadowsocksr_gtk::app::App::setup_action_channel::h6e75cce89f0680ed
                               at src/app.rs:115
  30:     0x5652e0366c66 - shadowsocksr_gtk::app::App::init::{{closure}}::hd49e6422f5c22131
                               at src/app.rs:95
  31:     0x5652e03695e0 - glib::source::trampoline::h560b177abbd9a036
                               at /home/gmg/.cargo/registry/src/code.aliyun.com-738b7dba08a2a41e/glib-0.8.2/src/source.rs:105
  32:     0x7ff4ccf62414 - <unknown>
  33:     0x7ff4ccf62c0e - g_main_context_dispatch
  34:     0x7ff4ccf64af0 - <unknown>
  35:     0x7ff4ccf64b2f - g_main_context_iteration
  36:     0x7ff4cd11da4d - g_application_run
  37:     0x5652e0364214 - <O as gio::application::ApplicationExtManual>::run::hd36a58155a313453
                               at /home/gmg/.cargo/registry/src/code.aliyun.com-738b7dba08a2a41e/gio-0.7.0/src/application.rs:23
  38:     0x5652e0362028 - shadowsocksr_gtk::app::App::run::h0667ef28d8d3e8aa
                               at src/app.rs:153
  39:     0x5652e035d349 - shadowsocksr_gtk::main::h27c20677e941d971
                               at src/main.rs:101
  40:     0x5652e036faf0 - std::rt::lang_start::{{closure}}::h5878424a70f24803
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  41:     0x5652e03d4c13 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  42:     0x5652e03d4c13 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  43:     0x5652e03db22a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  44:     0x5652e03d56cd - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  45:     0x5652e03d56cd - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  46:     0x5652e03d56cd - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  47:     0x5652e036fac9 - std::rt::lang_start::hf96c448981a7ab83
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  48:     0x5652e035d37a - main
  49:     0x7ff4ccd13e0b - __libc_start_main
  50:     0x5652e035c16a - _start
  51:                0x0 - <unknown>
```

**Comment by GuillaumeGomez** [comment]
So I assume that `sidebar` is a `ListBox`. Then maybe removing a row while using `foreach` is making troubles? I wonder if we check in the `foreach` function that the type is indeed existing before sending it... Based on the [code](https://github.com/gtk-rs/gtk/blob/master/src/auto/container.rs#L200-L207), we don't check if the `Widget` is `Some`.

**Comment by gmg137** [comment]
I have found the cause of the problem, the download is a complete example, but I don't know how to fix it.
```
extern crate gio;
extern crate gtk;

use gio::prelude::*;
use gtk::prelude::*;
use std::env::args;

#[macro_export]
macro_rules! clone {
    (@param _) => ( _ );
    (@param $x:ident) => ( $x );
    ($($n:ident),+ => move || $body:expr) => (
        {
            $( let $n = $n.clone(); )+
            move || $body
        }
    );
    ($($n:ident),+ => move |$($p:tt),+| $body:expr) => (
        {
            $( let $n = $n.clone(); )+
            move |$(clone!(@param $p),)+| $body
        }
    );
}

#[macro_export]
macro_rules! upgrade_weak {
    ($x:ident, $r:expr) => {{
        match $x.upgrade() {
            Some(o) => o,
            None => return $r,
        }
    }};
    ($x:ident) => {
        upgrade_weak!($x, ())
    };
}

fn build_ui(application: &gtk::Application) {
    let window = gtk::ApplicationWindow::new(application);

    window.set_title("First GTK+ Program");
    window.set_border_width(10);
    window.set_position(gtk::WindowPosition::Center);
    window.set_default_size(350, 70);

    let gtkbox = gtk::Box::new(gtk::Orientation::Vertical, 2);
    let button = gtk::Button::new();
    let label = gtk::Label::new_with_mnemonic(Some("remove row"));
    button.add(&label);
    gtkbox.pack_start(&button, true, true, 0);

    let listbox = gtk::ListBox::new();
    let label = gtk::Label::new(Some("listbox row 1"));
    label.set_halign(gtk::Align::Start);
    label.set_valign(gtk::Align::Fill);
    label.set_margin_start(18);
    label.set_max_width_chars(16);
    let row1 = gtk::ListBoxRow::new();
    row1.set_property_height_request(53);
    row1.add(&label);
    listbox.add(&row1);

    // This code no longer crashes after commenting
    //listbox.connect_row_selected(move |_, row| {
    //println!("row: {}", row.as_ref().unwrap().get_index());
    //});

    gtkbox.pack_end(&listbox, true, true, 0);

    let listbox_weak = listbox.downgrade();
    button.connect_clicked(clone!(listbox_weak=>move|_| {
        let listbox = upgrade_weak!(listbox_weak);
        listbox.foreach(|r|{
            // Crash here
            listbox.remove(r);
        });
    }));

    window.add(&gtkbox);

    window.show_all();
}

fn main() {
    let application =
        gtk::Application::new(Some("com.github.gtk-rs.examples.basic"), Default::default())
            .expect("Initialization failed...");

    application.connect_activate(|app| {
        build_ui(app);
    });

    application.run(&args().collect::<Vec<_>>());
}
```

**Comment by GuillaumeGomez** [comment]
Oh so the problem wasn't `foreach`. Also, you're not supposed to just `unwrap` things.

**Comment by gmg137** [comment]
May I ask how you get the right of the selected line id ?

**Comment by GuillaumeGomez** [comment]
What is the "right"?

**Comment by gmg137** [comment]
Sorry, I am using Google Translate.  .  .  .  I want to know how to get the id of the selected line?

**Comment by GuillaumeGomez** [comment]
Oh I see! I would do it like this:

```rust
listbox.connect_row_selected(move |_, row| {
    if let Some(row) = row {
        println!("row: {}", row.get_index());
    }
});
```

**Comment by EPashkin** [comment]
or use https://gtk-rs.org/docs/gtk/trait.ListBoxExt.html#tymethod.get_selected_row

**Comment by gmg137** [comment]
alright, thank you very much！
